name: Automated Workflow | Tech Challenge - FIAP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: ubuntu-latest
    

    env:
      Solution_Name: TechChallengeFiapMicrosserviceConsumerDeleteContact.sln
      ProjectTest_Name:  TCFiapConsumerDeleteContact.Tests/TCFiapConsumerDeleteContact.Tests.csproj
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGENAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Remove existing NuGet source
        run: dotnet nuget remove source github || echo "Source not found, skipping removal"
      
      - name: Configure NuGet credentials
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/caiofabiogomes/index.json" \
            --name github \
            --username caiofabiogomes \
            --password ${{ secrets.SECRET_NUGET_PACKAGES }} \
            --store-password-in-clear-text
      
   
